Greeting しゃべるように機能を追加した
su-its/ams-backend pull request #67
Opened 2021-03-16 14:13 UTC by h-takeyeah

何が変わったのか
- 入室・退室の別によって挨拶をするようになった．
- TSDocで関数の説明を書いた．
何ができてないのか
- 再生するのファイルがまだ用意できていない．

[TSDoc](https://tsdoc.org/)はまだTSのドキュメンテーションの記法のスタンダードと定められてはいませんが，ほぼスタンダードなのでこれに従いました．このPRで書いたTSの書き方でいいかどうかチェックしてもらって書き方の合意を取れれば取りたいです．ただ書き方の議論で時間を消費するのは本意ではないので，長引きそうだったらドキュメンテーション部分は外してコミットし直すかもしれません．

「書き方」: 例えば`/** */`と1行で書くのを許すか否か，`@params`は最後に書くか最初に書くか，summary(最初の`@`のない部分)の後は1行開けるか，など．

レビューお願いします．

2021-03-16 14:54 UTC, Stroheim001 approved these changes
TSdoc化への対応お疲れ様でした

後輩たちがみてちゃんとわかるようになると良いな～と思います。

自分は今回の修正ではそれほど、気にならなかったのですが、表記ゆれなどが起きてるなら、それは問題だと思うので、議題になると思います。

2021-03-16 16:22 UTC, equal-l2 requested changes

2021-03-16 16:22 UTC, equal-l2 commented on app/controllers/readerInputController.ts
> +   * `status`が適切かどうかを判定する。
「適切」をもっと噛み砕いて、具体的にどういう条件を判定するか書いた方がいいです

2021-03-16 16:27 UTC, equal-l2 commented
Redpenのエラーは #66 によるリグレッションなので無視して大丈夫です

2021-03-17 07:43 UTC, h-takeyeah commented on app/controllers/readerInputController.ts
> +   * `status`が適切かどうかを判定する。
書き直しました

2021-03-17 15:57 UTC, merged