asyncを使っているのに生かしてなかったのを修正。型を追加
su-its/ams-backend pull request #73
Opened 2021-03-17 13:30 UTC by h-takeyeah

Promiseにまつわるエラーハンドリングのやり方を修正したのとそれに合わせて型を作りました．

`models/`以下のファイルに書かれた関数は基本的に0番目に結果，1番目にあればエラーを含む配列を返すようになっていました．これを結果だけを返し，mysqlがエラーをthrowしても放置するように変更しました．

これらの関数はもとより全てasync functionなのでmysqlがエラーをthrowするとreject()に流れます．それを今まで生かしてなかったので，今回，呼び出し側の`controllers/`以下のファイルに書かれた関数に`try catch`を書いて例外処理をするように変更したというわけです．こうするとreturnに書かれるものが必然的にPromiseがfulfillされたときのものになり，エディタの補完が少し便利になります．

それからSQLのスキーマに対応するTSの型を作りました．`models/`側で返す前にSQLクエリを発行した結果をチェックした上でこの型で型アサーションして返すことで呼び出し側での補完が少し便利になります．

```typescript
// model側
type InRoomUser = {
  'user_id': number,
  'entered_at': Date
}
async function getUser (userId: number): Promise<InRoomUser> {}

// controller側
try {
  // 今までany[]だったものがInRoomUser[]になるので便利
  const user = await table.getUser(parseInt(req.params.user_id))
  //...以下略
} catch (err) {
  // rejectされたらここに来る
  console.error('[!] Error', err)
}
```

レビューよろしくお願いします．

2021-03-17 16:13 UTC, equal-l2 commented
自分は例外が**メチャクチャ嫌い**なので、個人的にはこの変更は受け入れ難いです。
(もちろん責任者はあなたなので、そう決めたなら従うまでですが……)

このPRが実現したい利益はなんですか？
戻り値の型を明確にしたいのであれば[tuple type](https://www.typescriptlang.org/docs/handbook/2/objects.html#tuple-types)や専用のオブジェクト型を作ることでも対応できます。

2021-03-17 16:16 UTC, equal-l2 commented
全くの参考として出しておくと、自分が好んで使うRust言語では、エラーは[Resultと呼ばれるEnum型](https://qiita.com/nirasan/items/321e7cc42e0e0f238254#result-%E3%81%A8%E3%81%AF)(Typescriptで言うunion型?)で表現されます。

2021-03-18 07:03 UTC, h-takeyeah commented
なるほど．エラーハンドリングを上位に持ってくるのは確かに気持ち悪かったですね．その変更はやめます

2021-03-18 07:17 UTC, h-takeyeah commented
このPRが実現したいことはエラーハンドリングのやり方を変更することでした．Promiseを返してくれるのだからその例外処理はtry，catchに任せればいいし，正常系だけ考えれば良くなるし，行数も減って良いかなと思ったので．

型を作ったのはおまけですが，使えますかね？

2021-03-18 07:53 UTC, equal-l2 commented
確かに今回の場合だとエラーが起こる可能性はかなり低いし異常が起こったら死ぬだけなのでこれでもいいかもしれないですね

2021-03-18 10:33 UTC, equal-l2 requested changes
まあ言われた要求からするとこのコードも存外悪くないかなという気分になってきました

2021-03-18 10:33 UTC, equal-l2 commented on app/controllers/accessLogsController.ts
> +    console.error(err)
ここ他のエラー出力に合わせてもうちょっと整形してあげてください
(「DBのエラー：<具体的なエラーの中身>」みたいなノリ)

2021-03-18 13:45 UTC, h-takeyeah commented on app/controllers/accessLogsController.ts
> +    console.error(err)
この修正はgreetingブランチの方に入れて，このPRは閉じますね

2021-03-18 16:14 UTC, equal-l2 commented
あれ、閉じちゃうんですか？
話を聞いていたら結構悪くないなと言う気になってきていたんですが。

(もし続けたいのであればReopenしてください)

2021-03-19 15:52 UTC, h-takeyeah commented
@equal-l2 これ以上やることはないのでレビューの上approveをお願いいたします．

2021-03-19 16:00 UTC, equal-l2 approved these changes

2021-03-19 16:00 UTC, merged