設定ファイルをyamlで置き換え
su-its/ams-backend pull request #79
Opened 2021-03-23 19:09 UTC by h-takeyeah

変更点
- 依存関係に[yaml](https://www.npmjs.com/package/yaml)を追加
- 新たに`config.yml`をルートに作成し，`config.ts`をそれを読む用のモジュールに改修
- 上の改修にともなって`.gitignore`を修正
- 不要になった`config.ts.sample`を削除

ルートにconfigなんちゃらというファイルが2つあるという少し気持ち悪いことになっています．メインの`ams-backend-server.ts`および`app/`以下のファイル群を変更せずにyamlを読めるようにしたかったのでこうしました．`app/config`ディレクトリを新たに作成し，`config.ts`をそこに放り込んでルートから消すこともできますので気になったらおっしゃってください．

---

(以下，自分用メモ)
[js-yaml](https://www.npmjs.com/package/js-yaml)パッケージの方が人気があるようだが，あえてyamlパッケージを採用した．
- js-yamlは関数`load`(JSONで言うと`parse`)の返り値がanyではなかったので使いにくかった．
- どうせプロパティのチェックは自前でやるのでloadの返り値はanyがありがたい(アサーションすればいい話ではあるが無駄)．
- その点yamlは同等の関数`parse`の返り値がanyなので非常にありがたい．
- yamlはパッケージサイズがjs-yamlに比べて約1/7とコンパクト．

2021-03-23 22:40 UTC, equal-l2 requested changes

2021-03-23 22:40 UTC, equal-l2 commented on config.yml.sample
> +  host: localhost
この辺は文字列なら`""`で括っといた方が親切かもです
(急に出てくると「こういうキーワードがあるのかな？」になってしまった）

2021-03-23 22:40 UTC, equal-l2 commented on config.ts
> +    (typeof arg.port === 'number' || typeof arg.port === 'undefined') &&
`port`が`undefined`な場合はどういう扱いになりますか？

2021-03-23 22:40 UTC, equal-l2 commented on config.ts
> +import * as YAML from 'yaml'
自分はルートフォルダにはエントリポイント以外のtsはない方がいいと思います。
今後こういう「アプリ自体のロジックには関わらないもの」が追加される時のことを考えると、`app`以下に`utils`とか`misc`みたいなフォルダを掘ってそこに入れておくと良いかもしれません。

2021-03-23 22:40 UTC, equal-l2 commented on .gitignore
>  mqtt.beebotte.com.pem
もうMQTTは使わないはずなのでこの機会に消してしまってください

2021-03-23 23:00 UTC, Stroheim001 commented
ごめんなさい、今あさごはん終わったんですけど、これだとCONTRIBUTING.mdの書き換えとDocker書き換えないといけないですよね...
COTNTRIBUTINGは貴方達でも出来るかもしれませんが、Dockerは下手すると私じゃないと出来ないくらいの腹積もりでいます。(絶望)
というか、なんでローンチ間際にクリティカルな仕様変更を...

2021-03-23 23:02 UTC, equal-l2 commented
@h-takeyeah くんに聞いた話だと、設定ファイルがTSだとansibleと馬が合わないみたいな話だったと思います。

---

Dockerは私がやります。

2021-03-23 23:09 UTC, Stroheim001 commented
@equal-l2 まあ、書いていただけるのはありがたいんですけど、そのPR見るの私なんですよね？ｗｗ

そもそもconfigファイルがなんでtsにかかないといけないのかについては、正直最初に `.env` にしようぜって言いたかったことではありますが、まあお手伝いさんの分際で言うのもあれなので、ってことで言わなかったのですが、割とまじめにAnsbileのためだけに仕様変更加えるなら、

(将来のためであったとしても)怖いっちゃ怖いですね(所詮4台しか機材ないんで...あとAnsbileを提案してしまったのは私なので面積も出来ませんが...)

2021-03-23 23:18 UTC, equal-l2 commented
ではあなたにはそのPRは見ていただかないことにして、私が責任を負う形にします。

2021-03-23 23:31 UTC, Stroheim001 commented
@equal-l2 4月以降に関しては、もうメール来ようが電話かけようが、無理なものは無理なので...

ごめんなさい。一応、メンション出してくれれば動作確認くらいだったら休みの日します。(出来たらやるくらいの感覚でいてください)

2021-03-23 23:32 UTC, equal-l2 commented
その必要はありません。
4月以降は全てこちらで見るようにします。

2021-03-23 23:37 UTC, Stroheim001 commented
@equal-l2 win機持ってる奴が俺しかおらん、とか動作確認が俺しかおらんって状況じゃない限りは
基本的に話そのものも降ってこない前提でええね？

まあDockerについてはバインドマウント以外は基本コメントつけておいたので分からんって事にはならんと思うんですけど...
そこそこきれいに書いたつもりだし...

2021-03-23 23:38 UTC, equal-l2 commented
どんな状況になろうとも4月以降この案件に関してあなたに何かを投げるつもりはないということです。
必要なら一筆したためましょうか？

2021-03-23 23:43 UTC, Stroheim001 commented
@equal-l2 
いいよいいよｗｗ

君に言質を取りたいわけでもITSを悪に仕立て上げたいわけじゃなくて、作った人が私だから、面倒見てって言われたら断る材料がないね、ってだけの話だからｗ

今見たけど、そうね...なんで、dbのworkdirがそこなのか、だけ明記されてない以外でコメントがたらんってところはなさそうだったかな？

一応理由は書いておくと、そのdirにinitとmigrateのsqlが入ってるからアタッチシェルしたときすぐセットアップ出来るやん、ってだけだから、あまりかく動機がなかっただけです

2021-03-24 04:14 UTC, h-takeyeah commented on config.ts
> +    (typeof arg.port === 'number' || typeof arg.port === 'undefined') &&
portが指定されなかった場合3306が割り当てられます．同様にhostも指定されない場合はlocalhostが割り当てられます．

2021-03-24 04:14 UTC, h-takeyeah commented on config.ts
> +    (typeof arg.port === 'number' || typeof arg.port === 'undefined') &&
たぶんmysqlの仕様ですね

2021-03-24 04:19 UTC, equal-l2 commented on config.ts
> +    (typeof arg.port === 'number' || typeof arg.port === 'undefined') &&
その辺の隠れた仕様は怖いので、オプションの設定は全て`required`(`undefined`を許さない)ように変更してください。

2021-03-24 05:28 UTC, h-takeyeah commented on config.yml.sample
> +  host: localhost
文字列は全て括りました

2021-03-24 05:29 UTC, h-takeyeah commented on config.ts
> +    (typeof arg.port === 'number' || typeof arg.port === 'undefined') &&
config.yml.sampleにもportを追加しました．タイプガードも`undefined`を許さない仕様に変更しました

2021-03-24 05:30 UTC, h-takeyeah commented on .gitignore
>  mqtt.beebotte.com.pem
pem消しました

2021-03-24 05:34 UTC, h-takeyeah commented
ba6ce0ffa281fc2e9763527158b701ca94b72994 について補足

`waitForConnections`はDBとのコネクションを`createConnection()`で開いている限り，意味のないオプションだということが分かったので消しました．

[参考 mysql(mysql2の継承元)のREADME](https://github.com/mysqljs/mysql#pool-options)

2021-03-24 05:36 UTC, h-takeyeah commented on config.ts
> +import * as YAML from 'yaml'
自分もそれには賛成です．ですが，影響範囲が大きくなりそうなので別PRにしますね

2021-03-24 07:00 UTC, equal-l2 approved these changes

2021-03-24 07:07 UTC, merged